name: tests-payments

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd payments && npm install && npm run test:ci
        env:
          STRIPE_KEY: ${{secrets.PERSONAL_TEST_STRIPE_KEY}}
