name: tests-payments

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          PERSONAL_TEST_STRIPE_KEY: ${{secrets.PERSONAL_TEST_STRIPE_KEY}}
      - run: cd payments && npm install && npm run test:ci
